# Example Database Configurationgorp
#
# For using gorp, enable parseTime option on MySQL to serialize/deserialize time.Time.
#
# see: https://github.com/rubenv/sql-migrate/issues/2
#
# Also interpolateParams=true, to replace placement on database server.
#
# see: https://github.com/go-sql-driver/mysql/pull/309
# see: http://dsas.blog.klab.org/archives/52191467.html
development:
  dialect: mysql
  datasource: root:@/cstack_dev?parseTime=true&collation=utf8_general_ci&interpolateParams=true
  dir: db/migrations

test:
  dialect: mysql
  datasource: root:@/cstack_test?parseTime=true&collation=utf8_general_ci&interpolateParams=true
  dir: db/migrations
